### ISSUE TITLE
doesn't getAttribute need an argument?

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/func-adl-types-atlas#51]
In `Jet_v1` I see:

```python
    @func_adl_parameterized_call(lambda s, a, param_1: func_adl_servicex_xaodr25.type_support.cpp_generic_1arg_callback('getAttribute', s, a, param_1))
    @property
    def getAttribute(self) -> func_adl_servicex_xaodr25.type_support.index_type_forwarder[func_adl_servicex_xaodr25.str.str]:
        "A method"
        ...
```

But shouldn't there be a string argument to it?

**Comment by gordonwatts** [comment]
The output `yaml` looks good:

```yaml
      - name: getAttribute
        return_type: U
        arguments:
          - name: name
            type: str
        parameter_arguments:
          - name: attribute_type
            type: cpp_type[U]
        param_helper: type_support.index_type_forwarder
        param_type_callback: "lambda s, a, param_1: {{package_name}}.type_support.cpp_generic_1arg_callback('getAttribute', s, a, param_1)"

```

So likely the problem is in the type writer code.
